version: '2'

services:
  postgres:
    # restart: always
    image: postgres:9.5.5
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=p@ssw0rd!
      - POSTGRES_DB=openposdb
    volumes:
      - /opt/docker/postgresql/data:/var/lib/postgresql/data

  redis:
    # restart: always
    image: redis:latest
    ports:
      - "6379:6379"